export default (data, struct) => {
  let view = new Uint8Array(data);

  view.forEach((bits, i) => {
    let xbld = {};

    xbld.description = map[bits].description;
    xbld.id = bits;
    xbld.type = map[bits].type;
    xbld.subtype = map[bits].subtype;

    xbld.building = 0;
    xbld.road = 0;
    xbld.rail = 0;
    xbld.power = 0;
    xbld.highway = 0;

    // buildings
    if ((bits > 0x00 && bits <= 0x0D) || (bits >= 0x70 && bits <= 0xFF))
      xbld.building = bits;

    // road
    if ((bits >= 0x1D && bits <= 0x2B) || (bits >= 0x3F && bits <= 0x46) || bits == 0x4B || bits == 0x4C || (bits >= 0x51 && bits <= 0x59))
      xbld.road = bits;

    // rail
    if ((bits >= 0x2C && bits <= 0x3E) || (bits >= 0x45 && bits <= 0x48) || (bits >= 0x4D && bits <= 0x4E) || (bits >= 0x5A && bits <= 0x5B) || (bits >= 0x6C && bits <= 0x6F))
      xbld.rail = bits;

    // power
    if ((bits >= 0x0E && bits <= 0x1C) || bits == 0x43 || bits == 0x44 || bits == 0x47 || bits == 0x48 || bits == 0x4F || bits == 0x50 || bits == 0x5C)
      xbld.power = bits;

    // highway
    if ((bits >= 0x49 && bits <= 0x50) || (bits >= 0x5D && bits <= 0x6B))
      xbld.highway = bits;

    struct.tiles[i].XBLD = xbld;
  });
};

let map = {
  0x00: { description: null, type: null },
  0x01: { description: 'Rubble', type: 'building' },
  0x02: { description: 'Rubble', type: 'building' },
  0x03: { description: 'Rubble', type: 'building' },
  0x04: { description: 'Rubble', type: 'building' },
  0x05: { description: 'Radioactive waste', type: 'building' },
  0x06: { description: 'Trees', type: 'building' },
  0x07: { description: 'Trees', type: 'building' },
  0x08: { description: 'Trees', type: 'building' },
  0x09: { description: 'Trees', type: 'building' },
  0x0A: { description: 'Trees', type: 'building' },
  0x0B: { description: 'Trees', type: 'building' },
  0x0C: { description: 'Trees', type: 'building' },
  0x0D: { description: 'Small park', type: 'building' },
  0x0E: { description: 'Power lines', type: 'power' },
  0x0F: { description: 'Power lines', type: 'power' },
  0x10: { description: 'Power lines', type: 'power' },
  0x11: { description: 'Power lines', type: 'power' },
  0x12: { description: 'Power lines', type: 'power' },
  0x13: { description: 'Power lines', type: 'power' },
  0x14: { description: 'Power lines', type: 'power' },
  0x15: { description: 'Power lines', type: 'power' },
  0x16: { description: 'Power lines', type: 'power' },
  0x17: { description: 'Power lines', type: 'power' },
  0x18: { description: 'Power lines', type: 'power' },
  0x19: { description: 'Power lines', type: 'power' },
  0x1A: { description: 'Power lines', type: 'power' },
  0x1B: { description: 'Power lines', type: 'power' },
  0x1C: { description: 'Power lines', type: 'power' },
  0x1D: { description: 'Road (straight)', type: 'road' },
  0x1E: { description: 'Road (straight)', type: 'road' },
  0x1F: { description: 'Road (sloped)', type: 'road' },
  0x20: { description: 'Road (sloped)', type: 'road' },
  0x21: { description: 'Road (sloped)', type: 'road' },
  0x22: { description: 'Road (sloped)', type: 'road' },
  0x23: { description: 'Road (curve)', type: 'road' },
  0x24: { description: 'Road (curve)', type: 'road' },
  0x25: { description: 'Road (curve)', type: 'road' },
  0x26: { description: 'Road (curve)', type: 'road' },
  0x27: { description: 'Road', type: 'road' },
  0x28: { description: 'Road', type: 'road' },
  0x29: { description: 'Road', type: 'road' },
  0x2A: { description: 'Road', type: 'road' },
  0x2B: { description: 'Road', type: 'road' },
  0x2C: { description: 'Rails (straight)', type: 'rail' },
  0x2D: { description: 'Rails (straight)', type: 'rail' },
  0x2E: { description: 'Rails (slope)', type: 'rail' },
  0x2F: { description: 'Rails (slope)', type: 'rail' },
  0x30: { description: 'Rails (slope)', type: 'rail' },
  0x31: { description: 'Rails (slope)', type: 'rail' },
  0x32: { description: 'Rails (curve)', type: 'rail' },
  0x33: { description: 'Rails (curve)', type: 'rail' },
  0x34: { description: 'Rails (curve)', type: 'rail' },
  0x35: { description: 'Rails (curve)', type: 'rail' },
  0x36: { description: 'Rails (junction)', type: 'rail' },
  0x37: { description: 'Rails (junction)', type: 'rail' },
  0x38: { description: 'Rails (junction)', type: 'rail' },
  0x39: { description: 'Rails (junction)', type: 'rail' },
  0x3A: { description: 'Rails (X junction)', type: 'rail' },
  0x3B: { description: 'Rails (slope)', type: 'rail' },
  0x3C: { description: 'Rails (slope)', type: 'rail' },
  0x3D: { description: 'Rails (slope)', type: 'rail' },
  0x3E: { description: 'Rails (slope)', type: 'rail' },
  0x3F: { description: 'Tunnel entrance', type: 'road' },
  0x40: { description: 'Tunnel entrance', type: 'road' },
  0x41: { description: 'Tunnel entrance', type: 'road' },
  0x42: { description: 'Tunnel entrance', type: 'road' },
  0x43: { description: 'Road / power lines', type: 'power', subtype: 'road' },
  0x44: { description: 'Road / power lines', type: 'power', subtype: 'road' },
  0x45: { description: 'Road / rails', type: 'road', subtype: 'rail' },
  0x46: { description: 'Road / rails', type: 'road', subtype: 'rail' },
  0x47: { description: 'Rails / power lines', type: 'power', subtype: 'rail' },
  0x48: { description: 'Rails / power lines', type: 'power', subtype: 'rail' },
  0x49: { description: 'Highway (straight)', type: 'highway' },
  0x4A: { description: 'Highway (straight)', type: 'highway' },
  0x4B: { description: 'Highway / road', type: 'highway', subtype: 'road' },
  0x4C: { description: 'Highway / road', type: 'highway', subtype: 'road' },
  0x4D: { description: 'Highway / rails', type: 'highway', subtype: 'rail' },
  0x4E: { description: 'Highway / rails', type: 'highway', subtype: 'rail' },
  0x4F: { description: 'Highway / power lines', type: 'highway', subtype: 'power' },
  0x50: { description: 'Highway / power lines', type: 'highway', subtype: 'power' },
  0x51: { description: 'Suspension bridge', type: 'road' },
  0x52: { description: 'Suspension bridge', type: 'road' },
  0x53: { description: 'Suspension bridge', type: 'road' },
  0x54: { description: 'Suspension bridge', type: 'road' },
  0x55: { description: 'Suspension bridge', type: 'road' },
  0x56: { description: 'Road bridge', type: 'road' },
  0x57: { description: 'Road bridge', type: 'road' },
  0x58: { description: 'Road bridge', type: 'road' },
  0x59: { description: 'Road bridge', type: 'road' },
  0x5A: { description: 'Rail bridge', type: 'rail' },
  0x5B: { description: 'Rail bridge', type: 'rail' },
  0x5C: { description: 'Elevated power lines', type: 'power' },
  0x5D: { description: 'Onramp', type: 'highway' },
  0x5E: { description: 'Onramp', type: 'highway' },
  0x5F: { description: 'Onramp', type: 'highway' },
  0x60: { description: 'Onramp', type: 'highway' },
  0x61: { description: 'Highway', type: 'highway' },
  0x62: { description: 'Highway', type: 'highway' },
  0x63: { description: 'Highway', type: 'highway' },
  0x64: { description: 'Highway', type: 'highway' },
  0x65: { description: 'Highway', type: 'highway' },
  0x66: { description: 'Highway', type: 'highway' },
  0x67: { description: 'Highway', type: 'highway' },
  0x68: { description: 'Highway', type: 'highway' },
  0x69: { description: 'Cloverleaf intersection', type: 'highway' },
  0x6A: { description: 'Highway bridges', type: 'highway' },
  0x6B: { description: 'Highway bridges', type: 'highway' },
  0x6C: { description: 'Subway / rails', type: 'rail' },
  0x6D: { description: 'Subway / rails', type: 'rail' },
  0x6E: { description: 'Subway / rails', type: 'rail' },
  0x6F: { description: 'Subway / rails', type: 'rail' },
  0x70: { description: 'Lower-class homes', type: 'building' },
  0x71: { description: 'Lower-class homes', type: 'building' },
  0x72: { description: 'Lower-class homes', type: 'building' },
  0x73: { description: 'Lower-class homes', type: 'building' },
  0x74: { description: 'Middle-class homes', type: 'building' },
  0x75: { description: 'Middle-class homes', type: 'building' },
  0x76: { description: 'Middle-class homes', type: 'building' },
  0x77: { description: 'Middle-class homes', type: 'building' },
  0x78: { description: 'Luxury homes', type: 'building' },
  0x79: { description: 'Luxury homes', type: 'building' },
  0x7A: { description: 'Luxury homes', type: 'building' },
  0x7B: { description: 'Luxury homes', type: 'building' },
  0x7C: { description: 'Gas station', type: 'building' },
  0x7D: { description: 'Bed & breakfast inn', type: 'building' },
  0x7E: { description: 'Convenience store', type: 'building' },
  0x7F: { description: 'Gas station', type: 'building' },
  0x80: { description: 'Small office building', type: 'building' },
  0x81: { description: 'Office building', type: 'building' },
  0x82: { description: 'Warehouse', type: 'building' },
  0x83: { description: 'Cassidy\'s Toy Store', type: 'building' },
  0x84: { description: 'Warehouse', type: 'building' },
  0x85: { description: 'Chemical storage', type: 'building' },
  0x86: { description: 'Warehouse', type: 'building' },
  0x87: { description: 'Industrial substation', type: 'building' },
  0x88: { description: 'Construction', type: 'building' },
  0x89: { description: 'Construction', type: 'building' },
  0x8A: { description: 'Abandoned building', type: 'building' },
  0x8B: { description: 'Abandoned building', type: 'building' },
  0x8C: { description: 'Cheap apartments', type: 'building' },
  0x8D: { description: 'Apartments', type: 'building' },
  0x8E: { description: 'Apartments', type: 'building' },
  0x8F: { description: 'Nice apartments', type: 'building' },
  0x90: { description: 'Nice apartments', type: 'building' },
  0x91: { description: 'Condominium', type: 'building' },
  0x92: { description: 'Condominium', type: 'building' },
  0x93: { description: 'Condominium', type: 'building' },
  0x94: { description: 'Shopping center', type: 'building' },
  0x95: { description: 'Grocery store', type: 'building' },
  0x96: { description: 'Office building', type: 'building' },
  0x97: { description: 'Resort hotel', type: 'building' },
  0x98: { description: 'Office building', type: 'building' },
  0x99: { description: 'Office / Retail', type: 'building' },
  0x9A: { description: 'Office building', type: 'building' },
  0x9B: { description: 'Office building', type: 'building' },
  0x9C: { description: 'Office building', type: 'building' },
  0x9D: { description: 'Office building', type: 'building' },
  0x9E: { description: 'Warehouse', type: 'building' },
  0x9F: { description: 'Chemical processing', type: 'building' },
  0xA0: { description: 'Factory', type: 'building' },
  0xA1: { description: 'Factory', type: 'building' },
  0xA2: { description: 'Factory', type: 'building' },
  0xA3: { description: 'Factory', type: 'building' },
  0xA4: { description: 'Factory', type: 'building' },
  0xA5: { description: 'Factory', type: 'building' },
  0xA6: { description: 'Construction', type: 'building' },
  0xA7: { description: 'Construction', type: 'building' },
  0xA8: { description: 'Construction', type: 'building' },
  0xA9: { description: 'Construction', type: 'building' },
  0xAA: { description: 'Abandoned building', type: 'building' },
  0xAB: { description: 'Abandoned building', type: 'building' },
  0xAC: { description: 'Abandoned building', type: 'building' },
  0xAD: { description: 'Abandoned building', type: 'building' },
  0xAE: { description: 'Large apartment building', type: 'building' },
  0xAF: { description: 'Large apartment building', type: 'building' },
  0xB0: { description: 'Condominium', type: 'building' },
  0xB1: { description: 'Condominium', type: 'building' },
  0xB2: { description: 'Office park', type: 'building' },
  0xB3: { description: 'Office tower', type: 'building' },
  0xB4: { description: 'Mini-mall', type: 'building' },
  0xB5: { description: 'Theater square', type: 'building' },
  0xB6: { description: 'Drive-in theater', type: 'building' },
  0xB7: { description: 'Office tower', type: 'building' },
  0xB8: { description: 'Office tower', type: 'building' },
  0xB9: { description: 'Parking lot', type: 'building' },
  0xBA: { description: 'Historic office building', type: 'building' },
  0xBB: { description: 'Corporate headquarters', type: 'building' },
  0xBC: { description: 'Chemical processing', type: 'building' },
  0xBD: { description: 'Large factory', type: 'building' },
  0xBE: { description: 'Industrial thingamajig', type: 'building' },
  0xBF: { description: 'Factory', type: 'building' },
  0xC0: { description: 'Large warehouse', type: 'building' },
  0xC1: { description: 'Warehouse', type: 'building' },
  0xC2: { description: 'Construction', type: 'building' },
  0xC3: { description: 'Construction', type: 'building' },
  0xC4: { description: 'Abandoned building', type: 'building' },
  0xC5: { description: 'Abandoned building', type: 'building' },
  0xC6: { description: 'Hydroelectric power', type: 'building' },
  0xC7: { description: 'Hydroelectric power', type: 'building' },
  0xC8: { description: 'Wind power', type: 'building' },
  0xC9: { description: 'Natural gas power plant', type: 'building' },
  0xCA: { description: 'Oil power plant', type: 'building' },
  0xCB: { description: 'Nuclear power plant', type: 'building' },
  0xCC: { description: 'Solar power plant', type: 'building' },
  0xCD: { description: 'Microwave power receiver', type: 'building' },
  0xCE: { description: 'Fusion power plant', type: 'building' },
  0xCF: { description: 'Coal power plant', type: 'building' },
  0xD0: { description: 'City hall', type: 'building' },
  0xD1: { description: 'Hospital', type: 'building' },
  0xD2: { description: 'Police station', type: 'building' },
  0xD3: { description: 'Fire station', type: 'building' },
  0xD4: { description: 'Museum', type: 'building' },
  0xD5: { description: 'Park (big)', type: 'building' },
  0xD6: { description: 'School', type: 'building' },
  0xD7: { description: 'Stadium', type: 'building' },
  0xD8: { description: 'Prison', type: 'building' },
  0xD9: { description: 'College', type: 'building' },
  0xDA: { description: 'Zoo', type: 'building' },
  0xDB: { description: 'Statue', type: 'building' },
  0xDC: { description: 'Water pump', type: 'building' },
  0xDD: { description: 'Runway (straight)', type: 'building' },
  0xDE: { description: 'Runway (intersection)', type: 'building' },
  0xDF: { description: 'Pier', type: 'building' },
  0xE0: { description: 'Crane', type: 'building' },
  0xE1: { description: 'Control tower', type: 'building' },
  0xE2: { description: 'Control tower', type: 'building' },
  0xE3: { description: 'Seaport warehouse', type: 'building' },
  0xE4: { description: 'Airport building', type: 'building' },
  0xE5: { description: 'Airport building', type: 'building' },
  0xE6: { description: 'Tarmac', type: 'building' },
  0xE7: { description: 'F-15b', type: 'building' },
  0xE8: { description: 'Hangar', type: 'building' },
  0xE9: { description: 'Subway station', type: 'building' },
  0xEA: { description: 'Radar', type: 'building' },
  0xEB: { description: 'Water tower', type: 'building' },
  0xEC: { description: 'Bus station', type: 'building' },
  0xED: { description: 'Rail station', type: 'building' },
  0xEE: { description: 'Parking lot', type: 'building' },
  0xEF: { description: 'Parking lot', type: 'building' },
  0xF0: { description: 'Loading bay', type: 'building' },
  0xF1: { description: 'Top secret', type: 'building' },
  0xF2: { description: 'Cargo yard', type: 'building' },
  0xF3: { description: 'Mayor\'s house', type: 'building' },
  0xF4: { description: 'Water treatment plant', type: 'building' },
  0xF5: { description: 'Library', type: 'building' },
  0xF6: { description: 'Hangar', type: 'building' },
  0xF7: { description: 'Church', type: 'building' },
  0xF8: { description: 'Marina', type: 'building' },
  0xF9: { description: 'Missile silo', type: 'building' },
  0xFA: { description: 'Desalination plant', type: 'building' },
  0xFB: { description: 'Plymouth arcology', type: 'building' },
  0xFC: { description: 'Forest arcology', type: 'building' },
  0xFD: { description: 'Darco arcology', type: 'building' },
  0xFE: { description: 'Launch arcology', type: 'building' },
  0xFF: { description: 'Braun Llama-dome', type: 'building' },
};